channels:
  - pytorch
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9
  - numpy
  - pandas
  - ipython
  - ipykernel
  - matplotlib
  - pip:
    - scikit-learn
    - seaborn
    - tqdm
